//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> term_id { get; set; }
        public Nullable<System.DateTime> group_date { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> group_item { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Term Term { get; set; }
        public virtual User User { get; set; }
    }
}
