//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay()
        {
            this.PayMetas = new HashSet<PayMeta>();
        }
    
        public int ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> pay_sum { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<int> pay_status { get; set; }
        public string item_json { get; set; }
        public Nullable<int> pay_form { get; set; }
        public string pay_guild { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayMeta> PayMetas { get; set; }
    }
}
