//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        public int ID { get; set; }
        public Nullable<int> product_id { get; set; }
        public string pd_content { get; set; }
        public string pd_name { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
