//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Groups = new HashSet<Group>();
            this.ProductDescriptions = new HashSet<ProductDescription>();
            this.Collections = new HashSet<Collection>();
        }
    
        public int ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> product_date { get; set; }
        public Nullable<System.DateTime> product_update { get; set; }
        public string product_name { get; set; }
        public string product_guid { get; set; }
        public string product_password { get; set; }
        public Nullable<int> product_view { get; set; }
        public string product_content { get; set; }
        public Nullable<int> product_status { get; set; }
        public string product_img { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<int> product_percent { get; set; }
        public Nullable<bool> product_active { get; set; }
        public Nullable<int> product_inventory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDescription> ProductDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collections { get; set; }
    }
}
