//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMeta
    {
        public int ID { get; set; }
        public Nullable<int> user_id { get; set; }
        public string meta_key { get; set; }
        public string meta_value { get; set; }
    
        public virtual User User { get; set; }
    }
}
